AWSTemplateFormatVersion: "2010-09-09"
Description: Parametrized template designed for use with nested stacks. Abstracts a CodeBuild project.

Parameters:
  FunctionName:
    Type: String
  EnvName:
    Type: String
    AllowedValues:
      - generic
      - dev
      - stage
      - prod
  ParameterOverrides:
    Type: String
    Default: ""
    # Example: "--parameter-overrides ENV=dev"
  BaseImage:
    Type: String
    Default: "{{resolve:ssm:base-image:1}}"
  BucketName:
    Type: String
    Default: "{{resolve:ssm:lambda-bucket:1}}"
  CodeBuildDescription:
    Type: String
    Default: "Description not provided."
  CodeBuildRole:
    Type: String
    Default: "{{resolve:ssm:codebuild-role-arn:1}}"
  GithubUrl:
    Type: String
  WebhookPattern:
    Type: String
  WebhookExcludePattern:
    Type: String
    AllowedValues:
      - true
      - false
Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: !Ref CodeBuildDescription
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
        Type: LINUX_CONTAINER
        PrivilegedMode: True
        EnvironmentVariables:
          - Name: FUNCTION_NAME
            Type: PLAINTEXT
            Value: !Ref FunctionName
          - Name: ENV
            Type: PLAINTEXT
            Value: !Ref EnvName
          - Name: PARAMETER_OVERRIDES
            Type: PLAINTEXT
            Value: !Ref ParameterOverrides
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: IMAGE_REPO_NAME
            Type: PLAINTEXT
            Value: !Ref FunctionName
          - Name: BASE_IMAGE
            Type: PLAINTEXT
            Value: !Ref BaseImage
          - Name: BUCKET
            Type: PLAINTEXT
            Value: !Ref BucketName
      Name: !Ref FunctionName
      ServiceRole: !Ref CodeBuildRole
      Source:
        Auth:
          Type: OAUTH
        Location: !Ref GithubUrl
        Type: GITHUB
      TimeoutInMinutes: 30
      Triggers:
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: !Ref WebhookPattern
              ExcludeMatchedPattern: !Ref WebhookExcludePattern
        Webhook: True
