AWSTemplateFormatVersion: "2010-09-09"
Description: Parametrized template designed for use with nested stacks. Abstracts a CodeBuild project.

Parameters:
  FunctionName:
    Type: String
  EnvName:
    Type: String
    AllowedValues:
      - generic
      - dev
      - stage
      - prod
  ParameterOverrides:
    Type: String
    Default: ""
    # Example: "--parameter-overrides ENV=dev"
  BaseImage:
    Type: String
    Default: "{{resolve:ssm:base-image:1}}"
  BucketName:
    Type: String
    Default: "{{resolve:ssm:lambda-bucket:1}}"
  CodeBuildDescription:
    Type: String
    Default: "Description not provided."
  CodeBuildRole:
    Type: String
    Default: "{{resolve:ssm:codebuild-role-arn:1}}"
  OriginRepo:
    Type: String
Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: !Ref CodeBuildDescription
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
        Type: LINUX_CONTAINER
        PrivilegedMode: True
        EnvironmentVariables:
          - Name: FUNCTION_NAME
            Type: PLAINTEXT
            Value: !Ref FunctionName
          - Name: ENV
            Type: PLAINTEXT
            Value: !Ref EnvName
          - Name: PARAMETER_OVERRIDES
            Type: PLAINTEXT
            Value: !Ref ParameterOverrides
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: DESTINATION_REPO
            Type: PLAINTEXT
            Value: !Ref FunctionName
          - Name: BASE_IMAGE
            Type: PLAINTEXT
            Value: !Ref BaseImage
          - Name: BUCKET
            Type: PLAINTEXT
            Value: !Ref BucketName
          - Name: ORIGIN_REPO
            Type: PLAINTEXT
            Value: !Ref OriginRepo
      Name: !Ref FunctionName
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                docker: 18
            build:
              commands:
                - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
                - docker pull $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$ORIGIN_REPO:latest
                - docker tag $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$ORIGIN_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$DESTINATION_REPO:latest
                - |
                  docker run --rm \
                    -e "BUCKET=$BUCKET" \
                    -e "FUNCTION_NAME=$FUNCTION_NAME" \
                    -e "REGION=$AWS_DEFAULT_REGION" \
                    -e "ENV=$ENV" \
                    -e "PARAMETER_OVERRIDES=$PARAMETER_OVERRIDES" \
                    -i $IMAGE_URI:$IMAGE_TAG
                - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$DESTINATION_REPO:latest
