AWSTemplateFormatVersion: "2010-09-09"
Description: SQS queues for ITS DataHub.

Parameters:
  MessageRetentionPeriod:
    Type: Number
    Default: 345600 ## 4 days
    Description: Time in seconds SQS will keep the message in the queue.
  VisibilityTimeout:
    Type: Number
    Default: 600 ## 10 minutes
    Description: Time in seconds SQS will lock a message after being accessed (prevents duplicate message deliveries).

Resources:
  # Canary Output (Result) Queues
  ResultQueueDev:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: True
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      QueueName: ResultQueueDev.fifo
      VisibilityTimeout: !Ref VisibilityTimeout
  ResultQueueStage:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: True
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      QueueName: ResultQueueStage.fifo
      VisibilityTimeout: !Ref VisibilityTimeout
  ResultQueueProd:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: True
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      QueueName: ResultQueueProd.fifo
      VisibilityTimeout: !Ref VisibilityTimeout

  # Canary Input (Validation) Queues
  ValidationQueueDev:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      QueueName: ValidationQueueDev
      VisibilityTimeout: !Ref VisibilityTimeout
  ValidationQueueStage:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      QueueName: ValidationQueueStage
      VisibilityTimeout: !Ref VisibilityTimeout
  ValidationQueueProd:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      QueueName: ValidationQueueProd
      VisibilityTimeout: !Ref VisibilityTimeout

  # SSM parameters
    ResultQueueDevARN:
      Type: AWS::SSM::Parameter
      Properties:
        Name: ResultQueueDevARN
        Type: String
        Value: !GetAtt ResultQueueDev.Arn
    ResultQueueStageARN:
      Type: AWS::SSM::Parameter
      Properties:
        Name: ResultQueueStageARN
        Type: String
        Value: !GetAtt ResultQueueStage.Arn
    ResultQueueProdARN:
      Type: AWS::SSM::Parameter
      Properties:
        Name: ResultQueueProdARN
        Type: String
        Value: !GetAtt ResultQueueProd.Arn

    ValidationQueueDevARN:
      Type: AWS::SSM::Parameter
      Properties:
        Name: ValidationQueueDevARN
        Type: String
        Value: !GetAtt ValidationQueueDev.Arn
    ValidationQueueStageARN:
      Type: AWS::SSM::Parameter
      Properties:
        Name: ValidationQueueStageARN
        Type: String
        Value: !GetAtt ValidationQueueStage.Arn
    ValidationQueueProdARN:
      Type: AWS::SSM::Parameter
      Properties:
        Name: ValidationQueueProdARN
        Type: String
        Value: !GetAtt ValidationQueueProd.Arn
